global using EntityFrameworkCoreGuideNET8.Infrastructure.Domain.DTOs;
global using EntityFrameworkCoreGuideNET8.Infrastructure.Domain.Interfaces;
global using EntityFrameworkCoreGuideNET8.Infrastructure.Domain.Models;
global using Microsoft.EntityFrameworkCore;
